# -*- coding: utf-8 -*-

from collections import namedtuple
from superdict import SuperDict

from app.utils.constants import create_constants


# Signatures ------------------------------------------------------------------
RULE_FORMATS = create_constants('RULE_FORMATS', (
    'suricata', 'snort',
))

RULE_ACTIONS = create_constants('RULE_ACTIONS', (
    'pass', 'drop', 'reject', 'alert', 'log', 'activate', 'dynamic', 'sdrop',
))

DIRECTIONS = namedtuple('DIRECTIONS', 'UNIDIRECTIONAL BIDIRECTIONAL')(
                        '->', '<>')

SIGNATURE_AUTOGENERATED_NAME_FORMAT = "({sid}) {message}"

# SID generator options -------------------------------------------------------
SID_BASE_PREFIX_FORMAT = '%Y%m%d'
SID_BASE_LENGTH = 10

# Severities ------------------------------------------------------------------
SEVERITY_LEVELS = create_constants('SEVERITY_LEVELS', (
    'HIGH', 'MEDIUM', 'LOW',
))

SEVERITY_WEIGHTS = SuperDict({
    SEVERITY_LEVELS.HIGH: {
        'min': 0,
        'max': 75,
        'default': 20,
    },
    SEVERITY_LEVELS.MEDIUM: {
        'min': 76,
        'max': 150,
        'default': 100,
    },
    SEVERITY_LEVELS.LOW: {
        'min': 151,
        'max': 255,
        'default': 200,
    },
})

SEVERITY_LEVEL_TO_PRIORITY_MAP = SuperDict({
    SEVERITY_LEVELS.HIGH: 1,
    SEVERITY_LEVELS.MEDIUM: 2,
    SEVERITY_LEVELS.LOW: 3,
})

# TASK 753
SEVERITY_BASED_ON_CLASS_TYPE_PRIORITY_FLAG = -1
