# -*- coding: utf-8 -*-

import datetime
import uuid

from app.utils.encoding import smart_str

from .constants import (
    SID_BASE_LENGTH, SID_BASE_PREFIX_FORMAT,
    SIGNATURE_AUTOGENERATED_NAME_FORMAT,
)


def generate_sid():
    return uuid.uuid1().int >> 65


def generate_sid_base():
    sid = datetime.datetime.utcnow().strftime(SID_BASE_PREFIX_FORMAT)
    return int(sid.ljust(SID_BASE_LENGTH, '0'))


def generate_signature_name(rule_info):
    sid = smart_str(rule_info['sid'])
    message = smart_str(rule_info['message'])

    return smart_str(SIGNATURE_AUTOGENERATED_NAME_FORMAT
                     .format(sid=sid, message=message))
